In [2]:
import numpy as np
import tensorflow as tf

2023-07-26 14:16:09.788357: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [5]:
import pandas as pd

In [6]:
dataset = pd.read_csv(r'/Users/KHL/Downloads/breast_cancer.csv')

In [7]:
X = dataset.iloc[:, 2:-1].values

In [9]:
dataset['diagnosis'] = dataset['diagnosis'].replace({'M': 0,"B": 1})

In [103]:
print("There Is No Value Are Duplicate:",dataset.duplicated().sum())

There Is No Value Are Duplicate: 0


In [104]:
dataset.describe()

id  diagnosis  radius_mean  texture_mean  perimeter_mean  \
count       569.0000   569.0000     569.0000      569.0000        569.0000   
mean   30371831.4323     0.6274      14.1273       19.2896         91.9690   
std   125020585.6122     0.4839       3.5240        4.3010         24.2990   
min        8670.0000     0.0000       6.9810        9.7100         43.7900   
25%      869218.0000     0.0000      11.7000       16.1700         75.1700   
50%      906024.0000     1.0000      13.3700       18.8400         86.2400   
75%     8813129.0000     1.0000      15.7800       21.8000        104.1000   
max   911320502.0000     1.0000      28.1100       39.2800        188.5000   

       area_mean  smoothness_mean  compactness_mean  concavity_mean  \
count   569.0000         569.0000          569.0000        569.0000   
mean    654.8891           0.0964            0.1043          0.0888   
std     351.9141           0.0141            0.0528          0.0797   
min     143.5000           0.0526            0.0194          0.0000   
25%     420.3000           0.0864            0.0649          0.0296   
50%     551.1000           0.0959            0.0926          0.0615   
75%     782.7000           0.1053            0.1304          0.1307   
max    2501.0000           0.1634            0.3454          0.4268   

       concave points_mean  ...  radius_worst  texture_worst  perimeter_worst  \
count             569.0000  ...      569.0000       569.0000         569.0000   
mean                0.0489  ...       16.2692        25.6772         107.2612   
std                 0.0388  ...        4.8332         6.1463          33.6025   
min                 0.0000  ...        7.9300        12.0200          50.4100   
25%                 0.0203  ...       13.0100        21.0800          84.1100   
50%                 0.0335  ...       14.9700        25.4100          97.6600   
75%                 0.0740  ...       18.7900        29.7200         125.4000   
max                 0.2012  ...       36.0400        49.5400         251.2000   

       area_worst  smoothness_worst  compactness_worst  concavity_worst  \
count    569.0000          569.0000           569.0000         569.0000   
mean     880.5831            0.1324             0.2543           0.2722   
std      569.3570            0.0228             0.1573           0.2086   
min      185.2000            0.0712             0.0273           0.0000   
25%      515.3000            0.1166             0.1472           0.1145   
50%      686.5000            0.1313             0.2119           0.2267   
75%     1084.0000            0.1460             0.3391           0.3829   
max     4254.0000            0.2226             1.0580           1.2520   

       concave points_worst  symmetry_worst  fractal_dimension_worst  
count              569.0000        569.0000                 569.0000  
mean                 0.1146          0.2901                   0.0839  
std                  0.0657          0.0619                   0.0181  
min                  0.0000          0.1565                   0.0550  
25%                  0.0649          0.2504                   0.0715  
50%                  0.0999          0.2822                   0.0800  
75%                  0.1614          0.3179                   0.0921  
max                  0.2910          0.6638                   0.2075  

[8 rows x 32 columns]

In [10]:
y = dataset.iloc[:, 1].values

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [34]:
X_train

array([[1.005e+01, 1.753e+01, 6.441e+01, ..., 1.055e-01, 6.499e-02,
        2.894e-01],
       [1.080e+01, 2.198e+01, 6.879e+01, ..., 1.927e-01, 7.485e-02,
        2.965e-01],
       [1.614e+01, 1.486e+01, 1.043e+02, ..., 2.310e-01, 1.129e-01,
        2.778e-01],
       ...,
       [9.436e+00, 1.832e+01, 5.982e+01, ..., 1.144e-01, 5.052e-02,
        2.454e-01],
       [9.720e+00, 1.822e+01, 6.073e+01, ..., 0.000e+00, 0.000e+00,
        1.909e-01],
       [1.151e+01, 2.393e+01, 7.452e+01, ..., 3.630e-01, 9.653e-02,
        2.112e-01]])

In [21]:
pd.set_option('display.float_format', lambda x: '%.4f' %x)

In [40]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [51]:
from keras.layers import Dropout

In [105]:
ann = tf.keras.models.Sequential()

In [106]:
ann.add(tf.keras.layers.Dense(units=28, activation='relu'))
ann.add(Dropout(0.2))

In [107]:
ann.add(tf.keras.layers.Dense(units=26, activation='relu'))
ann.add(Dropout(0.2))

In [108]:
ann.add(tf.keras.layers.Dense(units=26, activation='relu'))
ann.add(Dropout(0.2))

In [109]:
ann.add(tf.keras.layers.Dense(units=26, activation='relu'))
ann.add(Dropout(0.2))

In [110]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [111]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [112]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 300)

Epoch 1/300
15/15 [==============================] - 8s 10ms/step - loss: 0.6599 - accuracy: 0.6505
Epoch 2/300
15/15 [==============================] - 0s 6ms/step - loss: 0.5492 - accuracy: 0.6813
Epoch 3/300
15/15 [==============================] - 0s 4ms/step - loss: 0.4640 - accuracy: 0.7341
Epoch 4/300
15/15 [==============================] - 0s 5ms/step - loss: 0.3885 - accuracy: 0.8066
Epoch 5/300
15/15 [==============================] - 0s 6ms/step - loss: 0.3394 - accuracy: 0.8813
Epoch 6/300
15/15 [==============================] - 0s 4ms/step - loss: 0.2851 - accuracy: 0.9143
Epoch 7/300
15/15 [==============================] - 0s 9ms/step - loss: 0.2238 - accuracy: 0.9341
Epoch 8/300
15/15 [==============================] - 0s 9ms/step - loss: 0.1984 - accuracy: 0.9473
Epoch 9/300
15/15 [==============================] - 0s 6ms/step - loss: 0.1670 - accuracy: 0.9538
Epoch 10/300
15/15 [==============================] - 0s 6ms/step - loss: 0.1567 - accuracy: 0.9582
Epoch 11

In [125]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.0001)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

4/4 [==============================] - 0s 4ms/step
[[0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]]


In [126]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[44  3]
 [ 1 66]]


0.9649122807017544

In [127]:
weights = ann.get_weights()
feature_importance_scores = np.mean(np.abs(weights[0]), axis=0)

In [128]:

for i,v in enumerate(feature_importance_scores):
 print('Feature: %0d, Score: %.5f' % (i,v))

Feature: 0, Score: 0.15306
Feature: 1, Score: 0.20330
Feature: 2, Score: 0.14830
Feature: 3, Score: 0.20733
Feature: 4, Score: 0.16158
Feature: 5, Score: 0.18710
Feature: 6, Score: 0.16951
Feature: 7, Score: 0.21678
Feature: 8, Score: 0.18793
Feature: 9, Score: 0.17442
Feature: 10, Score: 0.20815
Feature: 11, Score: 0.19276
Feature: 12, Score: 0.18744
Feature: 13, Score: 0.18203
Feature: 14, Score: 0.13691
Feature: 15, Score: 0.17396
Feature: 16, Score: 0.17345
Feature: 17, Score: 0.15334
Feature: 18, Score: 0.19428
Feature: 19, Score: 0.18177
Feature: 20, Score: 0.15403
Feature: 21, Score: 0.16711
Feature: 22, Score: 0.16791
Feature: 23, Score: 0.19179
Feature: 24, Score: 0.14852
Feature: 25, Score: 0.16443
Feature: 26, Score: 0.17689
Feature: 27, Score: 0.18178
